### ISSUE TITLE
Starting services errors

### ISSUE THREAD

**Issue by andrus** [yauhen-info/redis-race-condition-poc#2]
Hi @yauhen-info  , I am trying to run the latest version of the code, but having some issues (container `7c91eca633cd` is one of the `docker_rest-service` instances.

```
andrus ~/work/redis/redis-race-condition-poc: sh start_project.sh 
Creating network "docker_poc-app-network" with driver "bridge"
Creating docker_mysql-db_1 ... done
Creating docker_redis_1    ... done
Creating docker_rest-service_1 ... done
Creating docker_rest-service_2 ... done
Creating docker_rest-service_3 ... done

ERROR: for nginx  Container "7c91eca633cd" is unhealthy.
ERROR: for db_updater_service  Container "7c91eca633cd" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

```
andrus ~/work/redis/redis-race-condition-poc: sh test_scenario_1.sh 
docker_redis_1 is up-to-date
docker_mysql-db_1 is up-to-date
docker_rest-service_1 is up-to-date
docker_rest-service_2 is up-to-date
docker_rest-service_3 is up-to-date

ERROR: for test_scenario_1  Container "7c91eca633cd" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by yauhen-info** [comment]
Hi Andrus,
I’ve started taking a look.
Will get back to you with status update as soon as possible.

**Comment by yauhen-info** [comment]
I tried on `MacOS BigSur 11.4 Beta (20F5046g)` locally, and could not reproduce. Before running `sh start_project.sh`, I cleaned up all containers and images. 

I got the following (healthy) output. 
```
Digest: sha256:75a55d33ecc73c2a242450a9f1cc858499d468f077ea942867e662c247b5e412
Status: Downloaded newer image for nginx:latest
Creating docker_redis_1    ... done
Creating docker_mysql-db_1 ... done
Creating docker_rest-service_1 ... done
Creating docker_rest-service_2 ... done
Creating docker_rest-service_3 ... done
Creating docker_db_updater_service_1 ... done
Creating docker_nginx_1              ... done
Attaching to docker_db_updater_service_1, docker_nginx_1
nginx_1               | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1               | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1               | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
db_updater_service_1  | +--------+---------+
db_updater_service_1  | | name   | counter |
db_updater_service_1  | +--------+---------+
db_updater_service_1  | | game_1 |      17 |
db_updater_service_1  | +--------+---------+
```

In order to avoid misuse of docker images built at different script runs,
I made a change (461ad0a0675e11fcd817e9fab53997419715299e) which explicitly says to docker to rebuild all images from scratch at each run.
That should avoid potential issues with images; at least we will be sure that each image is rebuild every time.

If this doesn't help, could you let me know the environment you've tried to run it on, please?
Although we rely on docker here, but I want to be able to reproduce the issue on the environment most similar to yours, so I could investigate further.

**Comment by andrus** [comment]
Thanks for confirming. Looks like the problem was on my end - I had old Docker. After upgrading to 20.10.5 it all starts like in your document.
